theme = "ayu_evolve"

[editor]
cursorline = true
scrolloff = 8
mouse = false
rulers = [100]
color-modes = true
true-color = true
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"

[editor.file-picker]
max-depth = 3

[editor.indent-guides]
render = true
character = "▏"
